"""phase2_initial_schema

Revision ID: 0e161111579b
Revises: 698e3e71754c
Create Date: 2026-05-01 17:32:15.415359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e161111579b'
down_revision: Union[str, Sequence[str], None] = '698e3e71754c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_categories')),
    sa.UniqueConstraint('code', name='uq_pantry_categories_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned', name='user_status'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('ai_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('recipe_suggestion', 'meal_plan', 'ingredient_substitution', name='ai_request_type'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('pantry_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='ai_request_status'), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_requests'))
    )
    op.create_index('idx_ai_requests_status_created', 'ai_requests', ['status', 'created_at'], unique=False)
    op.create_index('idx_ai_requests_user_created', 'ai_requests', ['user_id', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_entity_created', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'cancelled', name='meal_plan_status'), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_index('idx_meal_plans_user_status_date', 'meal_plans', ['user_id', 'status', 'plan_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('expiry_reminder', 'ai_tip', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_channel', sa.Enum('in_app', 'push', 'email', name='delivery_channel'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_pending_schedule', 'notifications', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_notifications_user_deleted', 'notifications', ['user_id', 'deleted_at'], unique=False)
    op.create_index('idx_notifications_user_read_active', 'notifications', ['user_id', 'read_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('ocr_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Enum('uploaded', 'parsed', 'failed', name='ocr_parse_status'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ocr_receipts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_receipts'))
    )
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ocr_confirmed', 'ai_assisted', name='pantry_item_source'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('expiry_status', sa.Enum('fresh', 'warning', 'expired', name='expiry_status'), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_value > 0', name=op.f('ck_pantry_items_quantity_value_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['pantry_categories.id'], name=op.f('fk_pantry_items_category_id_pantry_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pantry_items_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_items'))
    )
    op.create_index('idx_pantry_items_user_deleted', 'pantry_items', ['user_id', 'deleted_at'], unique=False)
    op.create_index('idx_pantry_items_user_expiry_date_active', 'pantry_items', ['user_id', 'expiry_date'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_pantry_items_user_expiry_status_active', 'pantry_items', ['user_id', 'expiry_status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('ocr_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name_raw', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('quantity_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_unit', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ocr_candidates_ocr_confidence_range')),
    sa.CheckConstraint('quantity_value > 0', name=op.f('ck_ocr_candidates_ocr_quantity_value_positive')),
    sa.ForeignKeyConstraint(['receipt_id'], ['ocr_receipts.id'], name=op.f('fk_ocr_candidates_receipt_id_ocr_receipts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ocr_candidates_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_candidates')),
    sa.UniqueConstraint('receipt_id', 'name_normalized', 'quantity_value', 'quantity_unit', name='uq_ocr_candidates_dedup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_candidates')
    op.drop_index('idx_pantry_items_user_expiry_status_active', table_name='pantry_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_pantry_items_user_expiry_date_active', table_name='pantry_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_pantry_items_user_deleted', table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_table('ocr_receipts')
    op.drop_index('idx_notifications_user_read_active', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_notifications_user_deleted', table_name='notifications')
    op.drop_index('idx_notifications_pending_schedule', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_meal_plans_user_status_date', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index('idx_audit_logs_entity_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_ai_requests_user_created', table_name='ai_requests')
    op.drop_index('idx_ai_requests_status_created', table_name='ai_requests')
    op.drop_table('ai_requests')
    op.drop_table('users')
    op.drop_table('pantry_categories')
    # ### end Alembic commands ###
